config/routes.rb
Rabbithole::Application.routes.draw do

  devise_for :users

  root :to => 'home#index'

  get    "/home(.:format)",                       :to => "home#index",                       :as => :home

  get    "/messages(.:format)",                   :to => "messages#index",                   :as => :messages
  post   "/messages(.:format)",                   :to => "messages#create",                  :as => :messages_create
  get    "/messages/:id(.:format)",               :to => "messages#show",                    :as => :message
  get    "/messages/new(.:format)",               :to => "messages#new",                     :as => :new_message
  get    "/messages/:id/edit(.:format)",          :to => "messages#edit",                    :as => :edit_message
  put    "/messages/:id(.:format)",               :to => "messages#update",                  :as => :update_message
  delete "/messages/:id(.:format)",               :to => "messages#destroy",                 :as => :destroy_message
  post   "/messages/publish(.:format)",           :to => "messages#publish",                 :as => :messages_publish

end

app/models/message.rb
require 'bunny'

class Message < ActiveRecord::Base

  validates_length_of :body, :maximum=>160, :message=> I18n.t('activerecord.models.errors.message.body_too_long')

  belongs_to :from_user, :class_name => 'User', :foreign_key => :from_user_id
  belongs_to :to_user,   :class_name => 'User', :foreign_key => :to_user_id

  def self.publish message
    bunny = Bunny.new
    bunny.start
    exchange = bunny.exchange "rabbithole"
    exchange.publish "#{message.to_json}", :key => "message"
    bunny.stop
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :messages, :foreign_key => :from_user_id, :as => :from_messages
  has_many :messages, :foreign_key => :to_user_id, :as => :to_messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @message = Message.new
    @messages = Message.find_all_by_from_user_id current_user.id

    @users = {}
    User.all.collect { |user| @users[user.email] = user.id }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  def show
    @message = Message.where(:from_user_id => current_user.id).find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  def new
    @message = Message.new

    @users = {}
    User.all.collect { |user| @users[user.email] = user.id }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  def edit
    @users = {}
    User.all.collect { |user| @users[user.email] = user.id }
    @message = Message.where(:from_user_id => current_user.id).find(params[:id])
  end

  def publish
    logger.debug "Publishing message #{params[:message]}"

    Message.publish params[:message]

    respond_to do |format|
      format.html { redirect_to messages_path, notice: 'Message was successfully published.' }
    end
  end

  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to messages_path, notice: 'Message was successfully created.' }
      else
        format.html { redirect_to messages_path, error: 'There was an error processing the message'  }
      end
    end
  end

  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @message = Message.where(:from_user_id => current_user.id).find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_path }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/home/index.html.erb
<h1>Rabbit Hole</h1>
<p>This is just an example application</p>

<% unless user_signed_in? -%>
  <p><%= link_to 'Sign up as User', new_user_registration_path %></p>
  <p><%= link_to 'Sign in as User', new_user_session_path %></p>
<% end -%>

<% if user_signed_in? -%>
  <p><%= link_to 'Check and Publish messages', messages_path %></p>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rabbit Hole</title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div id="container">
      <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      <%- end -%>

      <% if user_signed_in? -%>
        <div id="user_login_box" style="float:right">
          <%= current_user.email %> |
          <%= link_to 'Home', home_path %> |
          <%= link_to 'My info', edit_user_registration_path %> |
          <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
        </div>
      <% end -%>
      <div style="clear:both"></div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_available_messages.html.erb
<h1>Available messages</h1>

<table>
  <tr>
    <th>From</th>
    <th>To</th>
    <th>Body</th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.from_user.email %></td>
    <td><%= message.to_user.email %></td>
    <td><%= message.body %></td>
    <td><%= link_to 'Show', message %></td>
    <td><%= link_to 'Destroy', message, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/messages/_form.html.erb
<%= form_for(@message, :url => messages_publish_path, :method => :post ) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from %><br />
    <%= f.text_field :from , :value => current_user.email, :disabled => :true %>
    <%= f.hidden_field :from_user_id, :value => current_user.id %>
  </div>
  <div class="field">
    <%= f.label :to %><br />
    <%= f.select :to_user_id, options_for_select(@users),{:include_blank => '---'}%><br />
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit "Publish" %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Post new message</h1>
<fieldset>
    <%= render 'form' %>
</fieldset>

<fieldset>
    <%= render 'available_messages' %>
</fieldset>

<%= link_to 'Back to Home', home_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>From:</b>
  <%= @message.from_user.email %>
</p>

<p>
  <b>To:</b>
  <%= @message.to_user.email %>
</p>

<p>
  <b>Body:</b>
  <%= @message.body %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>